# Generated by Django 4.1.6 on 2023-03-02 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='count',
            field=models.PositiveIntegerField(default=4, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
